// <auto-generated />
namespace task1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class m002 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m002));
        
        string IMigrationMetadata.Id
        {
            get { return "202503191301457_m002"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
