// <auto-generated />
using System.CodeDom.Compiler;
using System.Data.Entity.Migrations;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace task1.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class m17 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m17));

        string IMigrationMetadata.Id
        {
            get { return "202502241702199_m17"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
